select * from customer_analysis limit 

--Q1. What is the total revenue generated by male vs. female customers?
SELECT
    "Gender",
    ROUND(SUM("Purchase Amount "),2) AS total_revenue,
    COUNT(*) AS total_orders,
    ROUND(AVG("Purchase Amount "),2) AS avg_purchase
FROM customer_analysis
GROUP BY "Gender"
ORDER BY total_revenue DESC;


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT
    "Customer ID",
    "Gender",
    "Category",
    "Item Purchased",
    "Purchase Amount "
FROM customer_analysis
WHERE "Discount Applied"='Yes'
AND "Purchase Amount " >
(
SELECT AVG("Purchase Amount ")
FROM customer_analysis
)
ORDER BY "Purchase Amount " DESC;


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT
    "Item Purchased",
    ROUND(AVG("Review Rating"),2) AS avg_rating,
    COUNT(*) AS total_reviews
FROM customer_analysis
GROUP BY "Item Purchased"
ORDER BY avg_rating DESC,total_reviews DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT
    "Shipping Type",
    COUNT(*) AS total_orders,
    ROUND(AVG("Purchase Amount "),2) AS avg_purchase,
    ROUND(SUM("Purchase Amount "),2) AS total_revenue
FROM customer_analysis
GROUP BY "Shipping Type"
ORDER BY total_revenue DESC;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT
    "Subscription Status",
    COUNT(*) AS customers,
    ROUND(AVG("Purchase Amount "),2) AS avg_purchase,
    ROUND(SUM("Purchase Amount "),2) AS revenue
FROM customer_analysis
GROUP BY "Subscription Status";

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
    "Item Purchased",
    ROUND(
        100.0*
        SUM(CASE
                WHEN "Discount Applied"='Yes'
                THEN 1
                ELSE 0
            END)
/COUNT(*),2) AS discount_percentage
FROM customer_analysis
GROUP BY "Item Purchased"
ORDER BY discount_percentage DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH segments AS
(
SELECT
    "Customer ID",

CASE

WHEN "Previous Purchases"<=2
THEN 'New'

WHEN "Previous Purchases" BETWEEN 3 AND 7
THEN 'Returning'

ELSE 'Loyal'

END AS customer_segment

FROM customer_analysis
)

SELECT
customer_segment,
COUNT(*) total_customers
FROM segments
GROUP BY customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH ranked_products AS
(
SELECT

"Category",

"Item Purchased",

COUNT(*) total_orders,

ROW_NUMBER()

OVER(PARTITION BY "Category"

ORDER BY COUNT(*) DESC)

AS rank

FROM customer_analysis

GROUP BY

"Category",

"Item Purchased"

)

SELECT *

FROM ranked_products

WHERE rank<=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT

"Payment Method",

COUNT(*) total_transactions,

ROUND(SUM("Purchase Amount "),2) revenue,

ROUND(AVG("Purchase Amount "),2) avg_purchase

FROM customer_analysis

GROUP BY "Payment Method"

ORDER BY revenue DESC;

--Q10. What is the revenue contribution of each age group? 
SELECT

CASE

WHEN "Age" BETWEEN 18 AND 25 THEN '18-25'

WHEN "Age" BETWEEN 26 AND 35 THEN '26-35'

WHEN "Age" BETWEEN 36 AND 45 THEN '36-45'

WHEN "Age" BETWEEN 46 AND 55 THEN '46-55'

ELSE '55+'

END AS age_group,

ROUND(SUM("Purchase Amount "),2) total_revenue,

COUNT(*) customers

FROM customer_analysis

GROUP BY age_group

ORDER BY total_revenue DESC;
